// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8IXzXg3lwdP_9gaMsLqLoxrPQAmPRD4',
    appId: '1:93648632910:android:c0092230fcbd3b2622171f',
    messagingSenderId: '93648632910',
    projectId: 'localize-sri-lanka',
    storageBucket: 'localize-sri-lanka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiC1BqAiazs3HYxb_k1ScmZh89yg8xKh0',
    appId: '1:93648632910:ios:558db264ed995d6422171f',
    messagingSenderId: '93648632910',
    projectId: 'localize-sri-lanka',
    storageBucket: 'localize-sri-lanka.appspot.com',
    androidClientId: '93648632910-22bi42g4gopmfbc3vs360m6ecmp5sh0b.apps.googleusercontent.com',
    iosClientId: '93648632910-kqemfjffbl8up5tkec3dlr61m9dl1t4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.localizeSrilanka',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3TCjJgeEjbCl3j76TpQFryi9JlVlM2g',
    appId: '1:93648632910:web:22ff3980a58b71f022171f',
    messagingSenderId: '93648632910',
    projectId: 'localize-sri-lanka',
    authDomain: 'localize-sri-lanka.firebaseapp.com',
    storageBucket: 'localize-sri-lanka.appspot.com',
  );

}